In [1]:
import pandas as pd

In [2]:
games = pd.read_csv('../2015-08-games.csv')

/var/folders/96/0nx7bxn507l730bk4_1kv4sr0000gn/T/ipykernel_58773/1264160646.py:1: DtypeWarning: Columns (5,6) have mixed types. Specify dtype option on import or set low_memory=False.
  games = pd.read_csv('../2015-08-games.csv')

In [14]:
na_rows = games[games['white_elo'].isna() | games['black_elo'].isna()]

In [33]:
filtered_games = games[~games["moves"].str.startswith("1")]

In [34]:
filtered_games

Empty DataFrame
Columns: [white_name, black_name, date, white_elo, black_elo, eco, opening, time_control, termination, moves]
Index: []

In [17]:
games.to_parquet('../2015-08-games.parquet', engine="pyarrow", index=False)

In [2]:
games = pd.read_parquet('../2015-08-games.parquet', engine="pyarrow")

In [3]:
games

,white_name,black_name,date,white_elo,black_elo,eco,opening,time_control,termination,moves
0,paul2chess3,Andique,2015.07.31,1509,1623,C62,Ruy Lopez: Steinitz Defense,300+0,Normal,1. e4 e5 2. Nf3 Nc6 3. Bb5 d6 4. d4 exd4 5. Nx...
1,Shehewho,gentux,2015.07.31,1857,1963,B00,Owen Defense,180+0,Normal,1. e4 b6 2. d4 Bb7 3. Nc3 e6 4. Nf3 Bb4 5. Bd3...
2,Gaardon,ChessDragon24,2015.07.31,892,1345,B20,Sicilian Defense,300+0,Normal,1. e4 c5 2. d3 d6 3. Nd2 Nc6 4. Ngf3 Nf6 5. g3...
3,Romuald47,HACKERSHUNTER86,2015.07.31,1501,1474,A40,Queen's Pawn,300+0,Abandoned,1. d4 1-0
4,shouganai,MrBangBang,2015.07.31,1953,1872,A02,Bird Opening,300+0,Normal,1. f4 c5 2. Nf3 Nc6 3. e3 e6 4. Bb5 Nf6 5. Bxc...
...,...,...,...,...,...,...,...,...,...,...
2599847,rohjinwook,gunsti,2015.08.31,1681,1669,B32,Sicilian Defense: Franco-Sicilian Variation,360+10,Normal,1. e4 c5 2. Nf3 Nc6 3. d4 e6 4. d5 exd5 5. exd...
2599848,Sillywommers,Stefan33,2015.08.31,1695,1472,B30,Sicilian Defense: Old Sicilian,240+0,Normal,1. e4 { [%eval 0.11] } 1... c5 { [%eval 0.16] ...
2599849,OhNowISeeIt,rapidoyfuriioso,2015.08.31,1592,1791,C39,"King's Gambit Accepted, Allgaier Gambit",480+0,Normal,1. e4 { [%eval 0.06] } 1... e5 { [%eval 0.21] ...
2599850,enzoavancig9,P_Leo,2015.08.31,1108,1568,C20,Portuguese Opening,420+8,Normal,1. e4 { [%eval 0.17] } 1... e5 { [%eval 0.25] ...
2599851,ijk786,FA3ST,2015.08.31,1167,1388,A40,Horwitz Defense,600+0,Normal,1. d4 { [%eval 0.19] } 1... e6 { [%eval 0.17] ...